### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by sssserious** [akanuasiegbu/BiPOCO#2]
If I want to use a different dataset, how can I modify the add_to_json_file. py file

**Comment by sssserious** [comment]
Also, if I don't have the ST dataset, how much code should I fill in here
        if cfg.DATASET.NAME_SECOND =='st':
            # to extract ##_#### of st dataset 
            if self.split == 'train' or self.split == 'val':
                file_num = os.listdir(cfg.DATASET.ST_VID_DIR_TRAIN)
            else:
                file_num = os.listdir(cfg.DATASET.ST_VID_DIR_TEST)

            file_num.sort()
            vids = []
            for i in file_num:
                split =i.split('_')
                vids.append([int(split[0]), int(split[1][:-4])])
        
        elif cfg.DATASET.NAME_SECOND =='avenue':
            if self.split =='train' or self.split == 'val':
                vids=range(1,17)
            else:
                vids=range(1,22)


This means I have no idea about vids

**Comment by akanuasiegbu** [comment]
Hi for your first question of how to modify for a different dataset, you can take a look at lines 263 and 267 or line 274 and 278 of the add_to_json file and modify according, assuming that you are just trying to add the anomaly to the frame level. 

    # This is for ShangahiTech
    # for vid_num in vid_nums:
    #     traj_loc = open('/mnt/roahm/users/akanu/projects/AlphaPose/st_alphapose_out/test/{:02d}_{:04d}.avi/alphapose-results.json'.format(vid_num[0], vid_num[1]))
    #     mask_loc = '/mnt/workspace/datasets/shanghaitech/testing/test_pixel_mask/{:02d}_{:04d}.npy'.format(vid_num[0], vid_num[1])
    #     json_add_frame_level(traj_loc, mask_loc, vid_num = vid_num, save_dir='../output_pose_json_appended_st', dataset = 'st').


For your second comment/question regarding what to fill out, if you were to have downloaded the Avenue dataset or the ShanghaiTech dataset, you would see that much of the code rewritten is just formatting changes specific to the dataset. My advice would be to download a dataset for example Avenue and try running it first and then changing it for the specific dataset that you have

**Comment by sssserious** [comment]
> 嗨，关于如何修改不同数据集的第一个问题，您可以查看 add_to_json 文件的第 263 行和第 267 行或第 274 行和第 278 行，并据此进行修改，假设您只是尝试将异常添加到帧级别。
> 
> ```
> # This is for ShangahiTech
> # for vid_num in vid_nums:
> #     traj_loc = open('/mnt/roahm/users/akanu/projects/AlphaPose/st_alphapose_out/test/{:02d}_{:04d}.avi/alphapose-results.json'.format(vid_num[0], vid_num[1]))
> #     mask_loc = '/mnt/workspace/datasets/shanghaitech/testing/test_pixel_mask/{:02d}_{:04d}.npy'.format(vid_num[0], vid_num[1])
> #     json_add_frame_level(traj_loc, mask_loc, vid_num = vid_num, save_dir='../output_pose_json_appended_st', dataset = 'st').
> ```
> 
> 对于您关于要填写什么的第二个评论/问题，如果您下载了 Avenue 数据集或 ShanghaiTech 数据集，您会看到大部分重写的代码只是特定于数据集的格式更改。我的建议是下载一个数据集，例如 Avenue 并尝试先运行它，然后针对您拥有的特定数据集进行更改

感谢您的回答，但是最近我又遇到了新的问题，我使用了https://drive.google.com/drive/folders/1jO3RnkvOsR-VLdATyzeMDsGF7mAu5Qdl?usp=sharing中的PKL文件，并进行了测试，得到的准确率仅仅为0.7，但是文件中说明网站中的PKL文件是表现最好的，是我还有配置没有完成吗？我使用的是 in13_out13。

**Comment by akanuasiegbu** [comment]
Please provide more detail, unclear what you did. Looking back at the README, did you follow Step 4: To evaluate AUC score and changed what it said?
![image](https://github.com/user-attachments/assets/be9c515e-fbc3-4bbb-b25e-0e143485881a)

**Comment by sssserious** [comment]
> Please provide more detail, unclear what you did. Looking back at the README, did you follow Step 4: To evaluate AUC score and changed what it said? ![image](https://private-user-images.githubusercontent.com/51218092/382481621-be9c515e-fbc3-4bbb-b25e-0e143485881a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MTMwNjgsIm5iZiI6MTczMDYxMjc2OCwicGF0aCI6Ii81MTIxODA5Mi8zODI0ODE2MjEtYmU5YzUxNWUtZmJjMy00YmJiLWIyNWUtMGUxNDM0ODU4ODFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDA1NDYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNjg5Njc2YWMxOTI5ZTE3Y2FhNTM4MzI5ZDYzYmY1ODkwNTk5ZDQ5ZTc5ZjBkM2ViMWNjMmQ4MGI0NzUxOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HmoMYjrSVPQqaxZvwgz17l1TzJDzuA6RUodvu_Kfdrc)

I downloaded the PKL file, changed the directory in main.py, and then ran main.py. The execution result is as follows:
(hy)  root@autodl-container-bbbc11ba52-7f79a5b0 :~/autl-tmp/BiPOCO-main# python experiments_code/main.py 
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/autodl-tmp/BiPOCO-main/custom_functions/visualizations_pose.py:360: RuntimeWarning: More than 20 figures have been opened.  Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
fig,ax = plt.subplots(nrows=1, ncols=1, figsize=(10,5))
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)
/root/miniconda3/envs/hy/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated.  If you meant to do this, you must specify 'dtype=object' when creating the ndarray
return array(a, dtype, copy=False, order=order)

Input Seq: 13, Output Seq: 13
Metric: l2, avg_or_max: avg
Use kp confidence: True
auc_frame:0.709963420171196
Done


The configuration of config/config.py during runtime is as follows:

exp = {
'data': 'avenue', #st, avenue, hr-avenue, hr-st
'data_consecutive': True,
'model_name': 'bitrap', 
'pose':True,
'use_kp_confidence': True,
'K': 1,
'plot_images':False, # Plot images
}
hyparams = {  
'input_seq': 13,
'pred_seq': 13,
'metric': 'l2',
'avg_or_max': 'avg', #avg
'errortype': 'error_flattened', #'error_summed' or 'error_flattened'
'to_xywh': True, # This is assuming file is in tlbr format
}

The pkl: file_to_load='/root/autl-tmp/BiPOCO-main/bitrap/outputs/JAAD_outses/goal_cvae_outses/unimoda_avenue_pose_ human_comnstrain/aussian_avenue_in_13_out_13_K_1_pose _hc_endpoint. pkl' used in main. py is downloaded from the best performing websites

**Comment by akanuasiegbu** [comment]
For you ran that is correct, Look at Table 2 of the paper more closely. I don't remember what your problem was and since you deleted your previous post I can't even refer back to it to see. If you are trying to get the best results for Avenue dataset, this should do it. Refer to the table 2.

```
hyparams = {
'input_seq': 3,
'pred_seq': 3,
'metric': 'l2',
'avg_or_max': 'avg', #avg
'errortype': 'error_flattened', #'error_summed' or 'error_flattened'
'to_xywh': True, # This is assuming file is in tlbr format
}
file_to_load = gaussian_avenue_in_3_out_3_K_1_pose_hc_endpoint.pkl
```

**Comment by akanuasiegbu** [comment]
The number in green is the one that you run above where **you got  auc_frame:0.709963420171196**. Note that the file name has "_pose _hc_endpoint " meaning that only endpoint loss was used. 
![image](https://github.com/user-attachments/assets/7673b582-6442-4cc0-9bb8-c81e85c3c6a5)

**Comment by sssserious** [comment]
> 绿色的数字是您运行上方**得到 auc_frame：0.709963420171196** 的数字。请注意，文件名具有 “_pose _hc_endpoint ”，表示仅使用了端点丢失。 ![图像](https://private-user-images.githubusercontent.com/51218092/382576306-7673b582-6442-4cc0-9bb8-c81e85c3c6a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MjM1MDAsIm5iZiI6MTczMDcyMzIwMCwicGF0aCI6Ii81MTIxODA5Mi8zODI1NzYzMDYtNzY3M2I1ODItNjQ0Mi00Y2MwLTliYjgtYzgxZTg1YzNjNmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDEyMjY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4OTlmNjQzODUxNjA0NGVhMWIxNDViMDExMTg2YWUwOGRiNzRjYjZmYWNjMGIxN2I5NWNiNzMzMGE3NWMzMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TVyT75PPNdKPl60wCsxkfV5488sLVD0Z8RvplQRt3rI)

This is my mistake, thank you for your patient answer. Your response has greatly helped me. Finally, I would like to know how to obtain the HR versions of the dataset 'avenue' and 'st'. Do I need to download them? Wishing you a pleasant day.

**Comment by akanuasiegbu** [comment]
HR versions are just subsets of their original datasets, so you don't need to download a different dataset.
