### ISSUE TITLE
About ST Dataset

### ISSUE THREAD

**Issue by m794643h** [akanuasiegbu/BiPOCO#3]
Hello, I recently tested on the st dataset and found that under the B-J error, the training could not obtain the data in the paper when the prediction sequence was 5. After training several times, the best was only 0.713, which was far from 0.735. Is there a problem with the given yml configuration file? Can you give detailed parameter settings?

**Comment by akanuasiegbu** [comment]
I have two questions:

1. To clarify, are you training the model from scratch using the B-J loss for an input and output sequence of 5, and then conducting inference on the trained model?
2. If so, could you provide more details about the modifications you already made for training with the B-J loss?

**Comment by m794643h** [comment]
> I have two questions:
> 
>     1. To clarify, are you training the model from scratch using the B-J loss for an input and output sequence of 5, and then conducting inference on the trained model?
> 
>     2. If so, could you provide more details about the modifications you already made for training with the B-J loss?

Hi, I trained it completely. I found that after modifying vid_train and vid_test in st_pose_hc.yml to the corresponding parts in the st dataset, line 25 of datasets/poses_n_box_torch would report an error, so I changed it 
if self.split == 'train' or self.split == 'val':
                for i in file_num:
                    split =i.split('_')
                    vids.append([int(split[0]), int(split[1][:-4])])
            else:
                for i in file_num:
                    split =i.split('_')
                    vids.append([int(split[0]), int(split[1])])
No other changes

**Comment by akanuasiegbu** [comment]
Thanks for providing more detail but I'm still unclear on a couple of things. **Please make sure to see number 3 below**

1. Are you using the [ train and test poses found here as input](https://drive.google.com/drive/folders/1vlTAnjrAG4CrKcBPxS138hbtRasF7fzM)? As that might change the results if not
![image](https://github.com/user-attachments/assets/449bcd41-6db2-47c7-a0e1-743fe68a1d7b)

2. Did you follow the instructions provided here, particularly regarding adjusting the input and output sequence lengths? You **must update the input and output sequence lengths** to 5 in both the `st_pose_hc.yml` file and the `bitrap/datasets/config_for_my_data.py` file.
![image](https://github.com/user-attachments/assets/22e1c983-95b3-433b-a980-13085993754a)

3. **IMPORTANT:** I forgot to include this in the README, but in the `st_pose_hc.yml` file, the default settings are `BONE: False`, `ENDPOINT: False`, and `JOINT: False`. To enable bone and joint loss, you need to update the settings to `BONE: True`, `ENDPOINT: False`, and `JOINT: True`.

4. Additional details: In the st_pose_hc.yml file, the parameter `ST_VID_DIR_TRAIN` specifies the folder containing all the training videos, while `ST_VID_DIR_TEST` points to the folder holding the test video. Based on the way I named it, it seems that the ShanghaiTech dataset originally provided test data as frames, which we converted into videos. 
![image](https://github.com/user-attachments/assets/b8557274-2f05-454f-959e-afef225a97e8)
![image](https://github.com/user-attachments/assets/26dee8c5-c608-4b3d-9b0c-ebce0d525542)

**Comment by akanuasiegbu** [comment]
I also have the trained models saved on the drive, so you can directly use them if needed. The model names indicate the loss type and input/output sequence length used. For example, `gua_in_3_out_3_k_1_hc_bone_endpoint` signifies that both bone and endpoint losses were used with an input and output sequence length of 3. Meanwhile, `gua_in_5_out_5_k_1_hc_bone` indicates that only bone loss was applied with an input and output sequence length of 5.
